### ISSUE TITLE
INFOGRAFÍA DIEGO GARCÍA BAUTISTA: REALIDAD AUMENTADA

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/infografia-ArteezyOne#1]
![INFOGRAFIA Diego_García_Bautista](https://user-images.githubusercontent.com/61806280/110060894-408dcd00-7d2c-11eb-81da-66d480de3922.png)

**Comment by Itzelzun** [comment]
Calif. 20

**Comment by Itzelzun** [comment]
Calificacion 20

**Comment by josealfredo79** [comment]
esta bien realizado y hecho.
